/**
 * @fileoverview gRPC-Web generated client stub for indexPackage
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.24.4
// source: proto/index.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';
import * as proto_index_pb from '../proto/index_pb';


export class ChatServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorChatInitiate = new grpcWeb.MethodDescriptor(
    '/indexPackage.ChatService/ChatInitiate',
    grpcWeb.MethodType.UNARY,
    proto_index_pb.InitiateRequest,
    proto_index_pb.InitiateResponse,
    (request: proto_index_pb.InitiateRequest) => {
      return request.serializeBinary();
    },
    proto_index_pb.InitiateResponse.deserializeBinary
  );

  chatInitiate(
    request: proto_index_pb.InitiateRequest,
    metadata: grpcWeb.Metadata | null): Promise<proto_index_pb.InitiateResponse>;

  chatInitiate(
    request: proto_index_pb.InitiateRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_index_pb.InitiateResponse) => void): grpcWeb.ClientReadableStream<proto_index_pb.InitiateResponse>;

  chatInitiate(
    request: proto_index_pb.InitiateRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_index_pb.InitiateResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/indexPackage.ChatService/ChatInitiate',
        request,
        metadata || {},
        this.methodDescriptorChatInitiate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/indexPackage.ChatService/ChatInitiate',
    request,
    metadata || {},
    this.methodDescriptorChatInitiate);
  }

  methodDescriptorSendMessage = new grpcWeb.MethodDescriptor(
    '/indexPackage.ChatService/SendMessage',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_index_pb.MessageRequest,
    google_protobuf_empty_pb.Empty,
    (request: proto_index_pb.MessageRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  sendMessage(
    request: proto_index_pb.MessageRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/indexPackage.ChatService/SendMessage',
      request,
      metadata || {},
      this.methodDescriptorSendMessage);
  }

  methodDescriptorChatStream = new grpcWeb.MethodDescriptor(
    '/indexPackage.ChatService/ChatStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_index_pb.StreamRequset,
    proto_index_pb.StreamMessage,
    (request: proto_index_pb.StreamRequset) => {
      return request.serializeBinary();
    },
    proto_index_pb.StreamMessage.deserializeBinary
  );

  chatStream(
    request: proto_index_pb.StreamRequset,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<proto_index_pb.StreamMessage> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/indexPackage.ChatService/ChatStream',
      request,
      metadata || {},
      this.methodDescriptorChatStream);
  }

  methodDescriptorUserStream = new grpcWeb.MethodDescriptor(
    '/indexPackage.ChatService/UserStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_index_pb.StreamRequset,
    proto_index_pb.UserStreamResponse,
    (request: proto_index_pb.StreamRequset) => {
      return request.serializeBinary();
    },
    proto_index_pb.UserStreamResponse.deserializeBinary
  );

  userStream(
    request: proto_index_pb.StreamRequset,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<proto_index_pb.UserStreamResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/indexPackage.ChatService/UserStream',
      request,
      metadata || {},
      this.methodDescriptorUserStream);
  }

}

